[package]
name = "media-format"
description = "Media container format demuxer and muxer registry"
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/media-format"
version.workspace = true
authors.workspace = true
license.workspace = true
categories = ["multimedia", "multimedia::audio", "multimedia::video"]
keywords = ["media", "container", "demuxer", "muxer"]
edition.workspace = true

[dependencies]
ctor.workspace = true
media-codec-types.workspace = true
media-core.workspace = true
media-format-types.workspace = true
media-format-isomp4 = { version = "0.1.0", default-features = false, path = "formats/isomp4", optional = true }

[features]
default = ["audio", "video", "demuxer", "all-formats"]
all-formats = ["all-demuxers", "all-muxers"]
all-demuxers = ["isomp4"]
all-muxers = []
audio = [
    "media-core/audio",
    "media-format-types/audio",
    "media-format-isomp4?/audio",
]
video = [
    "media-core/video",
    "media-format-types/video",
    "media-format-isomp4?/video",
]
demuxer = [
    "media-format-types/demuxer",
    "media-format-isomp4?/demuxer",
]
muxer = [
    "media-format-types/muxer",
    "media-format-isomp4?/muxer",
]
# Formats
isomp4 = ["dep:media-format-isomp4"]
