[package]
name = "media-codec-video-toolbox"
description = "A video codec implementation based on Apple VideoToolbox framework"
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/media-codec-video-toolbox"
version = "0.1.0"
authors.workspace = true
license.workspace = true
categories = ["multimedia::video", "multimedia::encoding"]
keywords = ["videotoolbox", "video", "codec", "media"]
edition.workspace = true

[dependencies]
media-codec-types = { workspace = true, default-features = false, features = ["video"] }
media-core = { workspace = true, features = ["video"] }
os-ver = "0.2.1"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
core-foundation.workspace = true
core-media.workspace = true
core-video.workspace = true
video-toolbox = "0.2.1"

[features]
default = ["decoder", "encoder"]
decoder = ["media-codec-types/decoder"]
encoder = ["media-codec-types/encoder"]

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"
target = [
    "x86_64-apple-darwin",
    "x86_64-apple-ios",
    "aarch64-apple-darwin",
    "aarch64-apple-ios",
]
