[package]
name = "media-codec"
description = "A generic encoding and decoding framework"
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/media-codec"
version.workspace = true
authors.workspace = true
license.workspace = true
categories = ["multimedia", "multimedia::audio", "multimedia::video", "multimedia::encoding"]
keywords = ["codec", "encoder", "decoder"]
edition.workspace = true

[dependencies]
ctor = "0.6"
media-codec-h264 = { version = "0.1.0", path = "codecs/h264", optional = true }
media-codec-h265 = { version = "0.1.0", path = "codecs/h265", optional = true }
media-codec-types.workspace = true
media-core.workspace = true

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
media-codec-video-toolbox = { version = "0.1.0", path = "codecs/video-toolbox", optional = true }

[features]
default = ["audio", "video", "decoder", "encoder"]
audio = [
    "media-core/audio",
    "media-codec-types/audio",
    "audio-codec",
]
video = [
    "media-core/video",
    "media-codec-types/video",
    "video-codec",
]
decoder = [
    "media-codec-types/decoder",
    "media-codec-h264?/decoder",
    "media-codec-h265?/decoder",
    "media-codec-video-toolbox?/decoder",
]
encoder = [
    "media-codec-types/encoder",
]
audio-codec = []
video-codec = ["h264", "h265", "video-toolbox"]
# Codecs
h264 = ["dep:media-codec-h264"]
h265 = ["dep:media-codec-h265"]
video-toolbox = ["dep:media-codec-video-toolbox"]
