[package]
name = "media-device"
description = "A cross-platform wrapper for capture and playback devices"
homepage.workspace = true
repository.workspace = true
documentation = "https://docs.rs/media-device"
version.workspace = true
authors.workspace = true
license.workspace = true
categories = ["multimedia", "multimedia::audio", "multimedia::video"]
keywords = ["audio", "video", "camera", "capture", "playback"]
edition.workspace = true

[dependencies.media-core]
workspace = true

[dependencies.media-device-types]
workspace = true

[dependencies]
media-device-camera = { workspace = true, optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen = "0.2"
web-time = "1.1"
js-sys = "0.3"

[target.'cfg(target_family = "wasm")'.dependencies.web-sys]
version = "0.3"
features = [
    "ImageData",
    "MediaDeviceInfo",
    "MediaDeviceKind",
    "MediaDevices",
    "MediaStream",
    "MediaStreamConstraints",
    "MediaStreamTrack",
    "MediaStreamTrackState",
    "MediaTrackConstraints",
    "MediaTrackSettings",
    "MediaTrackSupportedConstraints",
    "Navigator",
]

[target.'cfg(target_family = "wasm")'.dev-dependencies]
console_error_panic_hook = "0.1"

[dev-dependencies]
env_logger = "0.11"
log = "0.4"

[features]
default = ["audio", "video", "capture", "render", "all-devices"]
all-devices = ["all-capture-devices", "all-render-devices"]
all-capture-devices = ["av-foundation-capture", "media-foundation-capture"]
all-render-devices = []
audio = [
    "media-core/audio",
    "media-device-types/audio",
    "media-device-camera?/audio",
]
video = [
    "media-core/video",
    "media-device-types/video",
    "media-device-camera?/video",
]
capture = [
    "media-device-types/capture",
    "media-device-camera?/capture",
]
render = [
    "media-device-types/render",
]
# Devices
camera = ["dep:media-device-camera", "capture", "video"]
av-foundation-capture = ["camera", "media-device-camera?/av-foundation-capture"]
media-foundation-capture = ["camera", "media-device-camera?/media-foundation-capture"]

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = [
    "x86_64-pc-windows-msvc",
    "x86_64-apple-darwin",
    "x86_64-apple-ios",
    "aarch64-apple-darwin",
    "aarch64-apple-ios",
]
